export enum Types {
  SET_USER = "SET_USER",
  GET_ACCOUNT = "GET_ACCOUNT",
  GET_TRANS = "GET_TRANS",
  SET_SHARES = "SET_SHARES",
  GET_BUDGET = "GET_BUDGET",
  SET_BUDGET = "SET_BUDGET",
  SET_AUTH = "SET_AUTH",
  DELETE_TRANS = "DELETE_TRANS",
  ADD_TRANS = "ADD_TRANS",
  GET_MESSAGES = "GET_MESSAGES",
}
